#ifndef HDR_WINIOISOLATION_IOCTL
#define HDR_WINIOISOLATION_IOCTL

#if defined(USE_ON_KERNEL)
#include "fltBase.hpp"
#endif

#if defined(_MSC_VER)
#   pragma execution_character_set( "utf-8" )
#endif

#define WINIOISOLATION_DEVICE_TYPE 0x8227

#ifndef CTL_CODE

    //
    // Macro definition for defining IOCTL and FSCTL function control codes.  Note
    // that function codes 0-2047 are reserved for Microsoft Corporation, and
    // 2048-4095 are reserved for customers.
    //

    #define CTL_CODE( DeviceType, Function, Method, Access ) (                 \
        ((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method) \
    )

#endif

#ifndef METHOD_BUFFERED
#define METHOD_BUFFERED                 0
#endif

#ifndef FILE_ANY_ACCESS
#define FILE_ANY_ACCESS                 0
#endif

#define IOCTL_SET_DRIVER_CONFIG                 CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 1, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_GET_DRIVER_CONFIG                 CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 2, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_SET_DRIVER_STATUS                 CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 3, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_GET_DRIVER_STATUS                 CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 4, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_SET_STUB_CODE                     CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 5, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_GET_STUB_CODE                     CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 6, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_ADD_GLOBAL_POLICY                 CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 10, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_DEL_GLOBAL_POLICY_BY_MASK         CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 11, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_GET_GLOBAL_POLICY_COUNT           CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 12, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_RST_GLOBAL_POLICY                 CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 13, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_ADD_PROCESS_POLICY                CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 20, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_DEL_PROCESS_POLICY                CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 21, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_DEL_PROCESS_POLICY_BY_PID         CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 22, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_DEL_PROCESS_POLICY_BY_MASK        CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 23, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_GET_PROCESS_POLICY_COUNT          CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 24, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_GET_PROCESS_POLICY_ID_LIST        CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 25, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_GET_PROCESS_POLICY_BY_ID          CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 26, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_ADD_PROCESS_POLICY_ITEM           CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 27, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_DEL_PROCESS_POLICY_ITEM           CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 28, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_RST_PROCESS_POLICY                CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 29, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_FILE_GET_FILE_TYPE                CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 40, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_FILE_SET_SOLUTION_DATA            CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 41, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_FILE_GET_SOLUTION_DATA            CTL_CODE( WINIOISOLATION_DEVICE_TYPE, 0x800 + 42, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define IOCTL_FILE_ENCRYPT_FILE
#define IOCTL_FILE_DECRYPT_FILE

#define IOCTL_FILE_OPEND_ENCRYPTED_FILE_COUNT

#endif // HDR_WINIOISOLATION_IOCTL